openapi: 3.0.0
info:
  title: Meridian Fedramp Trust Center API Documentation
  version: 1.0.0
  description: ''
servers:
  - url: 7d7pdwb9t3.execute-api.us-east-1.amazonaws.com
paths:
  /prod/register:
    post:
      summary: Trust Center Registration
      tags: 
        - Trust Center Authentation
      responses:
        '200':
          description: "Success. Verification token is returned"
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
                    example: true
                  message:
                    type: string
                    example: Verification email sent
                  email:
                    type: string
                    format: email
                  next_steps:
                    type: string
        '400':
          description: "Validation Error"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Validation Error message
        '502':
          description: "Bad Gateway."
        '500':
          description: "Internal Server Error. An unexpected error occurred while processing the request."
      description: >-
        A Token is needed to access some feature of the Trust Center. The
        Register API can be used to begin the registration process. The Verify
        API is needed to complete the registration process and recieve the
        token.

        Email must be a .gov or .mil email address.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                agency:
                  type: string
                email:
                  type: string
                  format: email
                contact:
                  type: string
  /prod/verify:
    post:
      summary: Trust Center Verification
      tags: 
        - Trust Center Authentation
      responses:
        '200':
          description: "Success. Authentication token is returned."
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
                    example: true
                  token:
                    type: string
                    example: eyJhb...u9XCA
                  agency:
                    type: string
                  message:
                    type: string
                    example: Email verified successfully
                  next_steps:
                    type: string
        '400':
          description: "Validation Error"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Validation Error message
        '404':
          description: "Registrion Error"
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Registration not found or already verified
        '502':
          description: "Bad Gateway."
        '500':
          description: "Internal Server Error. Internal server error during registration." 
      description: >-
        A Token is needed to access some feature of the Trust Center. The
        Verify API is used to complete the registration process and recieve the
        token. The token required in this call is generated in the Register API
        call.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  example: eyJlbWF...Jkd0jPg
  /prod/status:
    get:
      summary: API Status Details
      tags: 
        - Operational
      responses:
        '200':
          description: Overall API Status Details, for the last hour"
          content:
            application/json:
              schema:
                type: object
                properties:
                  uptime_percent:
                    type: string
                  total_requests:
                    type: string
                  5xx_requests:
                    type: string
                  time_range_start:
                    type: string
                    format: datetime
                  time_range_end:
                    type: string
                    format: datetime
        '502':
          description: "Bad Gateway."
        '500':
          description: "Internal Server Error. Internal server error generating status." 
      description: Returns overall API health/status related data elements.
  /prod/config:
    get:
      summary: Meridan Secure Baseline system configurations
      tags:
        - Operational
      responses:
        '200':
          description: "Success. The baseline security config in formation is returned as a markdown file format."
          headers:
            Content-Type:
              description: "Indicates the file should be downloaded"
              schema:
                type: string
                example: "text/markdown; charset=UTF-8"
          content:
            text/markdown:
              schema:
                type: string
                example: Markdown Text
        '502':
          description: "Bad Gateway."
        '500':
          description: "Internal Server Error. Internal server error generating baseline security config." 
      description: Return the Meridian Secure Configuration baselines in a Markdown format.
  /prod/fedramp/inventory:
    get:
      summary: FedRAMP PMO inventory access (FRR-ADS-TC-05)
      tags: 
        - FedRAMP PMO
      responses:
        '200':
          description: Provides FedRAMP with list of registered agencies and access statistics
          content:
            application/json:
              schema:
                type: object
                properties:
                  inventory:
                    application/json:
                      schema:
                        type: object
                        properties:
                          agency:
                            type: string
                          email:
                            type: string
                            format: email
                          contact:
                            type: string
                          system_name:
                            type: string
                          registration_date:
                            type: string
                            format: datetime
                          status:
                            type: string
                          last_access:
                            type: string
                            format: datetime
                          package_downloads_30d:
                            type: integer
                          total_access_count_30d:
                            type: integer   
                  summary:
                    application/json:
                      schema:
                        type: object
                        properties:
                          total_registered_agencies:
                            type: integer
                          active_agencies_30d:
                            type: integer
                          total_package_downloads_30d:
                            type: integer
                          total_api_calls_30d:
                            type: integer   
                  generated_at:
                    type: datetime
                  period_days:
                    type: integer
        '502':
          description: "Bad Gateway."
        '500':
          description: "Internal Server Error. Internal server error generating inventory." 
      description: >-
        ## FedRAMP PMO Only Access

        Returns the required Fedramp Inventory in an JSON format, for
        FRR-ADS-TC-05. This contains a list of registered agencies and access
        statistics

        **Token is supplied by Meridian.**
      requestBody:
        headers:
            Authorization:
              description: "Bearer Token "
              schema:
                type: string
                example: "Bearer eyJhb...u9XCA"
  /prod/package:
    get:
      summary: Download the latest authorization package Zip file
      tags: 
        - Package Management
      responses:
        '200':
          description: "Success. The authorization package is returned as a ZIP file."
          headers:
            Content-Disposition:
              description: "Indicates the file should be downloaded as an attachment with a suggested filename."
              schema:
                type: string
                example: "attachment; filename=\"meridian-authorization-package-v1.2.3.zip\""
          content:
            application/zip:
              schema:
                type: string
                format: binary # Indicates the response is a file
        '401':
          description: "Unauthorized. The provided authentication token is missing, invalid, or expired."
        '502':
          description: "Bad Gateway."
        '500':
          description: "Internal Server Error. Internal server error generating baseline security config." 
      description: |-
        ##Registered Fedramp Agencies Only

        Returns a Zip file of the Meridian Fedramp Authorization Package file.

        **Token is supplied from the Verify API Call.**
      requestBody:
        headers:
            Authorization:
              description: "Bearer Token "
              schema:
                type: string
                example: "Bearer eyJhb...u9XCA"
  /prod/package/{filename}:
    get:
      summary: Download the latest authorization package individual file
      tags: 
        - Package Management
      responses:
        '200':
          description: "Success. The authorization package file is returned."
          headers:
            Content-Type:
              schema:
                type: string
                example: "application/json"
          content:
            application/json:
              schema:
                type: string
                format: string 
        '401':
          description: "Unauthorized. The provided authentication token is missing, invalid, or expired."
        '404':
          description: "Authorization package not yet available"
        '502':
          description: "Bad Gateway."
        '500':
          description: "Internal Server Error. Internal server error generating baseline security config." 
      description: >-
        ##Registered Fedramp Agencies Only

        Provides the ability to return each of the individual files created in
        the Meridian Fedramp Authorization Package per FRR-ADS-TC-03

        **Available Filenames**
         - 3pao_audit_report.json
         - assessed_vulnerabilities_integrated.json
         - assessed_vulnerabilities.json
         - fingerprint_cache.json
         - ksi_vulnerability_bridge_log.json
         - parsed_vulnerabilities.json
         - technical_validation_log.json
         - unified_ksi_validations.json
         - validation_consistency_log.json
         - vdr_vulnerability_status.json
      requestBody:
        headers:
            Authorization:
              description: "Bearer Token "
              schema:
                type: string
                example: "Bearer eyJhb...u9XCA"
